dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "shashank-ssriva-github"
    token:
      secure: "2t/R8olxBZmJBC+KZWjxLDF3ESqaMSnYWwGSypN2S7UvErRcKPc96kaFk+yknnLav/27Sg1ZyjObM4Hmi4CeSuKwexFGNgYPzMcrmNm/JBLnyOcmvCG89Mmb0pdFy3yUwVmwSEc9tKfmpxD8GUjgli5H+vd9bej2TopuI5N8lBHuln4FXPYjhiqMme1radlnxRGqztDOitf3NXKGv/8iuqHcRTzSEfu0+FFnF02vxy5yvtsEpSoGZpG+AaNv0YxA7Fm8q+s0VIwVqHiRbPuELFUW+2YjzSKVTrHNVJSY1663t4bXWLL6C7SMTOjuvSLKEmeRI3E6mEZH7svbAF3mhhPVSmqHdQjezf34uMqN2jVZOeCsPUlI4dQFLcecbw/uDLXJzL7jYzFB7sCelJS/ycJjK9sCwyWORK8yAWSofUCbDTVY2aebcXzdVakpQdpy56k4nJ6mz3qiDAfU9mrPY31rJyXpD0YP7kx1QhtBb/4K8S52E5BUQ+SYmuH0yTgcWgeJP29R5h2vJ1VcFnRZepk2QlaKoktnjTOkgz02CVB+tSlH+n4/YQxFlTmZqvFtwylEGYID9D0m4Nn6MZ10YRvOeR2o/13/khp0nif160GM6D451xZ2oOZWWqVhc2GFz4V+UYHPfRyT/iFdeofcKsdkprNOOwpERWMnr43XyKQ="
services:
  - docker

language: python

script:
  # sonar scanner
  - sonar-scanner


after_success:
  - test "$TRAVIS_BRANCH" = "master" && sh .deploy_scripts/deploy_heroku.sh
